### ISSUE TITLE
Thank you ❤️

### ISSUE THREAD

**Issue by marcuspoehls** [catdad/mock-stdio#9]
Hi Kiril,

thank you for your work on `mock-stdio`. I recently discovered this package due to @webpro’s recommendation. It immediately saved my problem and I since then integrated it in [Boost](https://boost.futurestud.io)’s testing utilities.

Keep up your work Kiril. Thank you! ❤️

**Comment by catdad** [comment]
😊🎊

I'm glad you found this helpful
